### Note: All synIDS are specific to the 2025 DREAM Olfactory Mixtures Prediction Challenge Final Round

In [1]:
import numpy as np
import pandas as pd
import synapseclient
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font
from scipy.stats import pearsonr
from scipy.spatial.distance import cosine as cosine_dist
from sklearn.metrics.pairwise import cosine_similarity



# Mapping for goldstandard and submission views by task
GOLDSTANDARD_SYNIDS = {1: "syn68736530", 2: "syn68736533"}
SUBMISSION_VIEWS = {"Task 1": "syn68879001", "Task 2": "syn68878940"}
INDEX_COL = "stimulus"

# Synapse login
syn = synapseclient.Synapse()
syn.login()

Welcome, Maria Diaz!

UPGRADE AVAILABLE

A more recent version of the Synapse Client (4.9.0) is available. Your version (4.4.0) can be upgraded by typing:
    pip install --upgrade synapseclient

Python Synapse Client version 4.9.0 release notes

https://python-docs.synapse.org/news/

## Functions to Extract ground truth, submissions, and their file data from Synapse

In [2]:
def load_goldstandard(syn, task):
    gold_synid = GOLDSTANDARD_SYNIDS[task]
    file_entity = syn.get(gold_synid, downloadFile=True)
    file_path = file_entity.path
    gold_df = pd.read_csv(file_path)
    return gold_df
    
#create try except where you try to get the team name from synapse and if it fails you just get the user
def get_name(id: str|int) -> str:
    try:
        return syn.getTeam(id).name
    except synapseclient.core.exceptions.SynapseHTTPError:
        try:
            return syn.getUserProfile(id).userName
        except synapseclient.core.exceptions.SynapseHTTPError:
            return "NA"
    except ValueError:
        return "NA - id is not correct"

def load_team_predictions(syn, submissions_df):
    team_dfs = []
    # No handling of the submission that's not recorded in the submission table 
    # for task 2 required given the late submission is not in the top 2 or 3
    for _, row in submissions_df.iterrows():
        team_id = row['submitterid']
        sub_id = row['id']
        file_path = syn.getSubmission(sub_id)['filePath']
        df = pd.read_csv(file_path)
        df = df.sort_values(INDEX_COL).reset_index(drop=True)
        feature_cols = [col for col in df.columns if col != INDEX_COL]
        rename_dict = {col: f"team_{team_id}_{col}" for col in feature_cols}
        df = df.rename(columns=rename_dict)
        df = df[[INDEX_COL] + list(rename_dict.values())]
        team_dfs.append(df)
    merged_df = team_dfs[0]
    for df in team_dfs[1:]:
        merged_df = pd.merge(merged_df, df, on=INDEX_COL, how='outer')
    return merged_df

def select_final_round_submissions(
    syn: synapseclient.Synapse, subview_id: str, evaluation_id: str
) -> pd.DataFrame:
    """
    Get final round submissions from synapse tables that include all submissions for both rounds.
    Outputs a final averaged rank and sorted leaderboard.
    Only submissions from the specified evaluation are considered.
    For each submitter, but one team, only the submission closest to August 8, 2025 is kept.
    If any of the IDs [9756929, 9756930, 9756939, 9756938, 9756943, 9756942] are present,
    keep only 9756929 if present, otherwise keep only 9756930 if present, and remove the rest.
    Also manually add the permitted late submission for Task 2.
    """

    query = (
        f"SELECT id, pearson_correlation, cosine, createdOn, submitterid FROM {subview_id} "
        f"WHERE score_status = 'SCORED' "
    )
    submissions = syn.tableQuery(query).asDataFrame()

    # Special handling for the specified IDs
    replace_ids = [9756929, 9756930, 9756939, 9756938, 9756943, 9756942]
    present_ids = [rid for rid in replace_ids if rid in submissions['id'].values]
    if present_ids:
        if 9756929 in present_ids:
            submissions = submissions[~submissions['id'].isin(replace_ids) | (submissions['id'] == 9756929)]
        elif 9756930 in present_ids:
            submissions = submissions[~submissions['id'].isin(replace_ids) | (submissions['id'] == 9756930)]
        else:
            submissions = submissions[~submissions['id'].isin(replace_ids)]
    
    # Keep both team_id (submitterid) and canonical team_name
    submissions['team_id'] = submissions['submitterid'].astype(str)
    submissions['team_name'] = submissions['team_id'].apply(get_name)

    # Only add late submission for Task 2
    if "Task 2" in evaluation_id or subview_id == SUBMISSION_VIEWS["Task 2"]:
        entity = syn.get("syn68843729", downloadFile=False)
        late_row = {
            "submitterid": entity.createdBy,
            "team_id": str(entity.createdBy),
            "team_name": get_name(entity.createdBy),
            "id": "syn68843729",
            "pearson_correlation": 0.6668633229642209,
            "cosine": 0.22813314634185586,
            "createdOn": 1754692655346,
        }
        submissions = pd.concat([submissions, pd.DataFrame([late_row])], ignore_index=True)

    # Find the submission closest to August 8, 2025 for each submitter
    target_date = int(pd.Timestamp("2025-08-08T23:59:59Z").timestamp() * 1000)
    submissions['createdOn_diff'] = np.abs(submissions['createdOn'] - target_date)
    submissions = submissions.sort_values(['submitterid', 'createdOn_diff'])
    submissions = submissions.groupby('submitterid', as_index=False).first()

    # Ranking
    submissions['pearson_rank'] = submissions['pearson_correlation'].rank(
        ascending=False, method="min", na_option='bottom')
    submissions['cosine_rank'] = submissions['cosine'].rank(
        ascending=True, method="min", na_option='bottom')
    submissions['final_rank'] = (
        submissions['pearson_rank'] + submissions['cosine_rank']) / 2

    # Select the top 3 ranked submissions for future bootstrapping
    top_submissions = submissions.nsmallest(3, 'final_rank')

    return submissions, top_submissions


def split_merged_to_team_dfs(merged_df, gold_df, index_col="stimulus"):
    """
    Convert merged_df from load_team_predictions into
    a dict of team_name -> dataframe with [index_col + gold attribute columns].
    Ensures predictors align with gold_df columns.
    """
    attr_cols = [c for c in gold_df.columns if c != index_col]
    team_dfs = {}

    for col in merged_df.columns:
        if col == index_col:
            continue

        # Parse out team_id from "team_<id>_<attr>"
        parts = col.split("_", 2)
        if len(parts) < 3:
            raise ValueError(f"Unexpected column format: {col}")
        team_id = parts[1]
        attr_name = parts[2]

        # Lookup canonical team_name via get_name
        team_name = get_name(team_id)

        # Initialize or extend this team's dataframe
        if team_name not in team_dfs:
            team_dfs[team_name] = merged_df[[index_col, col]].rename(columns={col: attr_name})
        else:
            team_dfs[team_name] = team_dfs[team_name].merge(
                merged_df[[index_col, col]].rename(columns={col: attr_name}),
                on=index_col,
                how="outer"
            )

    # Reorder each team_df to match gold_df attribute order
    for team_name in team_dfs:
        cols = [index_col] + attr_cols
        team_dfs[team_name] = team_dfs[team_name][cols]

    return team_dfs

def write_bootstrap_results_to_excel(bootstrap_results, out_file="bootstrap_results.xlsx"):
    """
    submissions_df : dict[int, pd.DataFrame]
        Dictionary of submissions dataframes, keyed by task index (1,2,...)
    bootstrap_results : dict[str, dict]
        Dictionary keyed by task name (e.g. "Task 1") with values being results
        from bootstrapping functions (can include multiple result tables).
    out_file : str
        Output Excel filename
    """
    with pd.ExcelWriter(out_file, engine="openpyxl") as writer:
        
        # === First sheet: initial submissions for Task 1 ===
        #submissions_df[1].to_excel(writer, sheet_name="Initial Submissions", index=False)
        
        # === Subsequent sheets: one per bootstrap result ===
        for task_name, results in bootstrap_results.items():
            for result_name, result in results.items():
                
                sheet_name = f"{task_name} - {result_name}"
                
                if isinstance(result, pd.DataFrame):
                    # Direct dataframe
                    result.to_excel(writer, sheet_name=sheet_name[:31], index=False)
                elif isinstance(result, dict):
                    # Convert dictionary to dataframe
                    pd.DataFrame([result]).to_excel(writer, sheet_name=sheet_name[:31], index=False)
                else:
                    # Fallback: store as string
                    pd.DataFrame([{"result": str(result)}]).to_excel(writer, sheet_name=sheet_name[:31], index=False)

    print(f"✅ Results written to {out_file}")

## Functions Applied in Ranking, Bootstrapping, and winner determination

In [3]:
def bootstrap_pairwise(
    gold_master,
    team_mats,
    team_names,
    baseline_tbl,
    metrics_on_rows,
    sample_frac=1.0,
    N=10000,
    random_state=98109,
    tie_tol=0.05
):
    """
    Bootstrap comparison between top-ranked teams.
    
    Returns
    -------
    pd.DataFrame
        Flat results with one row per comparison, suitable for Excel export.
    """
    rng = np.random.default_rng(random_state)
    n = gold_master.shape[0]
    B = max(1, round(n * sample_frac))

    # Define pairs: (1 vs 2), and (2 vs 3) if available
    pairs = [(baseline_tbl["team"].iloc[0], baseline_tbl["team"].iloc[1])]
    if baseline_tbl.shape[0] >= 3:
        pairs.append((baseline_tbl["team"].iloc[1], baseline_tbl["team"].iloc[2]))

    # Track results
    wins = {f"{a} vs {b}": 0 for (a, b) in pairs}
    ties = {f"{a} vs {b}": 0 for (a, b) in pairs}

    for _ in range(N):
        rows = rng.choice(n, size=B, replace=True)

        # Compute metrics for all teams on these rows
        met = []
        for nm in team_names:
            p, c = metrics_on_rows(rows, gold_master, team_mats[nm])
            met.append([p, c])
        met = np.array(met)
        
        # Ranking: smaller rank is better
        rP = np.argsort(np.argsort(-met[:, 0])) + 1  # rank on pearson (higher = better)
        rC = np.argsort(np.argsort(met[:, 1])) + 1   # rank on cosine (lower = better)
        avg = (rP + rC) / 2.0
        avg_dict = dict(zip(team_names, avg))

        # Compare each pair
        for (a, b) in pairs:
            if a not in avg_dict or b not in avg_dict:
                continue
            a_rank, b_rank = avg_dict[a], avg_dict[b]
            if np.isnan(a_rank) or np.isnan(b_rank):
                continue
            key = f"{a} vs {b}"
            if a_rank < b_rank:
                wins[key] += 1
            elif a_rank == b_rank:
                ties[key] += 1

    # ==== Flatten results into DataFrame ====
    rows_out = []
    for (a, b) in pairs:
        key = f"{a} vs {b}"
        p_win = (wins[key] + 0.5 * ties[key]) / N
        BF_odds = (p_win + 1e-8) / (1 - p_win + 1e-8)

        tie_flag = abs(p_win - 0.5) <= tie_tol
        rows_out.append({
            "team1": a,
            "team2": b,
            "wins": wins[key],
            "ties": ties[key],
            "p_win": p_win,
            "BF_odds": BF_odds,
            "N": N,
            "rows_per_draw": B,
            "sample_frac": sample_frac,
            "tie_flag": tie_flag
        })

    return pd.DataFrame(rows_out)



# def bootstrap_pwin(
#     gold_master,
#     team_mats,
#     team_names,
#     baseline_df,
#     sample_frac=1.0,
#     N=10000,
#     random_state=None,
#     tie_tol=1e-6
# ):
#     """
#     Run bootstrap to compute p_win, BF odds, and bootstrap_ties for top 2 teams, i.e. first place only.
#     """
#     rng = np.random.default_rng(random_state)
#     n = gold_master.shape[0]
#     B = max(1, round(n * sample_frac))
    
#     top2 = baseline_df["team"].iloc[:2].tolist()
#     wins = 0
#     ties = 0
    
#     for _ in range(N):
#         rows = rng.choice(n, size=B, replace=True)
#         met = {nm: metrics_on_rows(rows, gold_master, mat) for nm, mat in team_mats.items()}
#         pearsons = {nm: m[0] for nm, m in met.items()}
#         cosines  = {nm: m[1] for nm, m in met.items()}
        
#         df_tmp = pd.DataFrame({
#             "team": team_names,
#             "pearson": [pearsons[nm] for nm in team_names],
#             "cosine": [cosines[nm] for nm in team_names]
#         })
#         df_tmp["rP"] = df_tmp["pearson"].rank(ascending=False, method="average")
#         df_tmp["rC"] = df_tmp["cosine"].rank(ascending=True,  method="average")
#         df_tmp["avg"] = (df_tmp["rP"] + df_tmp["rC"]) / 2
#         avg_dict = df_tmp.set_index("team")["avg"].to_dict()
        
#         a1, a2 = avg_dict[top2[0]], avg_dict[top2[1]]
#         if np.isnan(a1) or np.isnan(a2):
#             continue
#         if a1 < a2: 
#             wins += 1
#         elif a1 == a2: 
#             ties += 1
    
#     p_win = (wins + 0.5 * ties) / N
#     BF_odds = (p_win + 1e-8) / (1 - p_win + 1e-8)

#     # ==== BOOTSTRAP TIE REPORT ====
#     bootstrap_ties = []
#     if abs(p_win - 0.5) <= tie_tol:
#         tied_place = float(baseline_df["average_rank"].iloc[0])  # baseline first place
#         bootstrap_ties.append({
#             "rank": tied_place,
#             "teams": top2
#         })

#     return {
#         "team1": top2[0],
#         "team2": top2[1],
#         "p_win": p_win,
#         "BF_odds": BF_odds,
#         "N": N,
#         "rows_per_draw": B,
#         "sample_frac": sample_frac,
#         "bootstrap_ties": bootstrap_ties
#     }

def bootstrap_pwin(
    gold_master,
    team_mats,
    team_names,
    baseline_df,
    metrics_on_rows,
    sample_frac=1.0,
    N=10000,
    random_state=None,
    tie_tol=0.05
):
    """
    Run bootstrap to compute p_win, BF odds, and tie_flag for top 2 teams.
    
    Returns a flat dictionary with tie_flag = True/False like bootstrap_pairwise.
    """
    rng = np.random.default_rng(random_state)
    n = gold_master.shape[0]
    B = max(1, round(n * sample_frac))
    
    top2 = baseline_df["team"].iloc[:2].tolist()
    wins = 0
    ties = 0
    
    for _ in range(N):
        rows = rng.choice(n, size=B, replace=True)
        met = {nm: metrics_on_rows(rows, gold_master, mat) for nm, mat in team_mats.items()}
        pearsons = {nm: m[0] for nm, m in met.items()}
        cosines  = {nm: m[1] for nm, m in met.items()}
        
        df_tmp = pd.DataFrame({
            "team": team_names,
            "pearson": [pearsons[nm] for nm in team_names],
            "cosine": [cosines[nm] for nm in team_names]
        })
        df_tmp["rP"] = df_tmp["pearson"].rank(ascending=False, method="average")
        df_tmp["rC"] = df_tmp["cosine"].rank(ascending=True,  method="average")
        df_tmp["avg"] = (df_tmp["rP"] + df_tmp["rC"]) / 2
        avg_dict = df_tmp.set_index("team")["avg"].to_dict()
        
        a1, a2 = avg_dict[top2[0]], avg_dict[top2[1]]
        if np.isnan(a1) or np.isnan(a2):
            continue
        if a1 < a2: 
            wins += 1
        elif a1 == a2: 
            ties += 1
    
    p_win = (wins + 0.5 * ties) / N
    BF_odds = (p_win + 1e-8) / (1 - p_win + 1e-8)
    tie_flag = abs(p_win - 0.5) <= tie_tol

    return {
        "team1": top2[0],
        "team2": top2[1],
        "p_win": p_win,
        "BF_odds": BF_odds,
        "N": N,
        "rows_per_draw": B,
        "sample_frac": sample_frac,
        "tie_flag": tie_flag
    }

In [4]:
def compute_baseline(gold_df, team_dfs, index_col="stimulus"):
    """
    Align gold and team dataframes to common IDs and compute baseline ranks.
    
    Parameters
    ----------
    gold_df : pd.DataFrame
        Gold standard dataframe.
    team_dfs : dict[str, pd.DataFrame]
        Dictionary of team name to dataframe mapping.
    index_col : str
        Name of the index column (default: "stimulus").

    Returns
    -------
    gold_master : np.ndarray
    team_mats : dict[str, np.ndarray]
    team_names : list[str]
    baseline_df : pd.DataFrame
    """
    # Identify attribute columns
    attr_cols = [c for c in gold_df.columns if c != index_col]
    if not attr_cols:
        raise ValueError("No attribute columns found besides index_col.")
    
    # Align to common IDs
    gold_ids = gold_df[index_col].astype(str)
    team_ids = [set(df[index_col].astype(str)) for df in team_dfs.values()]
    common_ids_all = set(gold_ids).intersection(*team_ids)
    if not common_ids_all:
        raise ValueError("No overlapping stimuli across all teams.")
    
    keep_gold = gold_df[index_col].astype(str).isin(common_ids_all)
    gold_master = gold_df.loc[keep_gold, attr_cols].to_numpy()
    order_ids = gold_df.loc[keep_gold, index_col].astype(str).tolist()
    
    team_mats = {}
    for nm, df in team_dfs.items():
        sub = df[df[index_col].astype(str).isin(common_ids_all)]
        sub = sub.set_index(index_col).reindex(order_ids)
        team_mats[nm] = sub[attr_cols].to_numpy()
    
    team_names = list(team_mats.keys())
    n = gold_master.shape[0]
    
    # Baseline metrics
    base_metrics = []
    for nm in team_names:
        p, c = metrics_on_rows(np.arange(n), gold_master, team_mats[nm])
        base_metrics.append([nm, p, c])
    baseline_df = pd.DataFrame(base_metrics, columns=["team","pearson","cosine"])
    
    baseline_df["rank_pearson"] = baseline_df["pearson"].rank(ascending=False, method="average")
    baseline_df["rank_cosine"]  = baseline_df["cosine"].rank(ascending=True,  method="average")
    baseline_df["average_rank"] = (baseline_df["rank_pearson"] + baseline_df["rank_cosine"]) / 2
    baseline_df = baseline_df.sort_values(
        ["average_rank","rank_pearson","rank_cosine","pearson","cosine"],
        ascending=[True,True,True,False,True]
    )
    
    return gold_master, team_mats, team_names, baseline_df

In [5]:
# def metrics_on_rows(rows, gold_mat, team_mat):
#     """Compute pearson and cosine between gold and team predictions on sampled rows."""
#     g = gold_mat[rows, :].ravel()
#     t = team_mat[rows, :].ravel()
#     if np.std(t) == 0 or np.std(g) == 0:
#         return np.nan, np.nan
#     pearson, _ = pearsonr(g, t)
#     cosine = 1 - cosine_similarity([g], [t])[0,0]  # lower = better
#     return pearson, cosine

def metrics_on_rows(rows, gold_master, team_matrix):
    """
    Compute row-wise Pearson and cosine similarity across features, 
    then average over all selected rows.

    Parameters
    ----------
    rows : array-like
        Indices of rows to sample.
    gold_master : np.ndarray
        Gold standard matrix (rows = stimuli, cols = features).
    team_matrix : np.ndarray
        Team predictions matrix (rows = stimuli, cols = features).

    Returns
    -------
    avg_pearson : float
        Mean Pearson correlation across selected rows.
    avg_cosine : float
        Mean cosine similarity across selected rows.
    """
    pearsons = []
    cosines = []
    
    for i in rows:
        g = gold_master[i, :]
        t = team_matrix[i, :]

        # skip rows with NaN
        if np.any(np.isnan(g)) or np.any(np.isnan(t)):
            continue

        # Pearson correlation
        if np.std(g) == 0 or np.std(t) == 0:
            p = 0.0  # define correlation as 0 if variance is zero
        else:
            p, _ = pearsonr(g, t)
            if np.isnan(p):
                p = 0.0

        # Cosine similarity (1 - cosine distance)
        if np.all(t == 0) or np.all(g == 0):
            c = 0.0  # avoid division by zero
        else:
            c = 1 - cosine_dist(g, t)

        pearsons.append(p)
        cosines.append(c)

    # Average across rows (like R script does)
    avg_pearson = np.mean(pearsons) if pearsons else np.nan
    avg_cosine = np.mean(cosines) if cosines else np.nan

    return avg_pearson, avg_cosine

def baseline_and_bootstrap(
    gold_df,
    team_dfs,
    metrics_on_rows,
    index_col="stimulus",
    sample_frac=1.0,
    N=10000,
    random_state=None,
    tie_tol=0.05  # <-- changeable default threshold dependent on use case
):
    """
    gold_df: dataframe with gold labels (must include index_col and attribute columns)
    team_dfs: dict[name -> dataframe] (each must include index_col and same attribute columns)
    """
    rng = np.random.default_rng(random_state)
    
    # Automatically infer attribute columns (everything except the index_col)
    attr_cols = [c for c in gold_df.columns if c != index_col]
    if not attr_cols:
        raise ValueError("No attribute columns found besides index_col.")
    
    # Align to common IDs
    gold_ids = gold_df[index_col].astype(str)
    team_ids = [set(df[index_col].astype(str)) for df in team_dfs.values()]
    common_ids_all = set(gold_ids).intersection(*team_ids)
    if not common_ids_all:
        raise ValueError("No overlapping stimuli across all teams.")
    
    keep_gold = gold_df[index_col].astype(str).isin(common_ids_all)
    gold_master = gold_df.loc[keep_gold, attr_cols].to_numpy()
    order_ids = gold_df.loc[keep_gold, index_col].astype(str).tolist()
    
    team_mats = {}
    for nm, df in team_dfs.items():
        sub = df[df[index_col].astype(str).isin(common_ids_all)]
        sub = sub.set_index(index_col).reindex(order_ids)
        team_mats[nm] = sub[attr_cols].to_numpy()
    
    team_names = list(team_mats.keys())
    n = gold_master.shape[0]
    
    # ==== BASELINE ====
    base_metrics = []
    for nm in team_names:
        p, c = metrics_on_rows(np.arange(n), gold_master, team_mats[nm])
        base_metrics.append([nm, p, c])
    baseline_df = pd.DataFrame(base_metrics, columns=["team","avg_pearson","avg_cosine"])
    
    baseline_df["rank_pearson"] = baseline_df["avg_pearson"].rank(ascending=False, method="average")
    baseline_df["rank_cosine"]  = baseline_df["avg_cosine"].rank(ascending=True,  method="average")
    baseline_df["average_rank"] = (baseline_df["rank_pearson"] + baseline_df["rank_cosine"]) / 2
    baseline_df = baseline_df.sort_values(
        ["average_rank","rank_pearson","rank_cosine","avg_pearson","avg_cosine"],
        ascending=[True,True,True,False,True]
    )
    
    top2 = baseline_df["team"].iloc[:2].tolist()
    
    # ==== BOOTSTRAP ====
    B = max(1, round(n * sample_frac))
    wins = 0
    ties = 0
    
    for _ in range(N):
        rows = rng.choice(n, size=B, replace=True)
        met = {nm: metrics_on_rows(rows, gold_master, mat) for nm, mat in team_mats.items()}
        pearsons = {nm: m[0] for nm, m in met.items()}
        cosines  = {nm: m[1] for nm, m in met.items()}
        
        df_tmp = pd.DataFrame({
            "team": team_names,
            "pearson": [pearsons[nm] for nm in team_names],
            "cosine": [cosines[nm] for nm in team_names]
        })
        df_tmp["rP"] = df_tmp["pearson"].rank(ascending=False, method="average")
        df_tmp["rC"] = df_tmp["cosine"].rank(ascending=True,  method="average")
        df_tmp["avg"] = (df_tmp["rP"] + df_tmp["rC"]) / 2
        avg_dict = df_tmp.set_index("team")["avg"].to_dict()
        
        a1, a2 = avg_dict[top2[0]], avg_dict[top2[1]]
        if np.isnan(a1) or np.isnan(a2):
            continue
        if a1 < a2: 
            wins += 1
        elif a1 == a2: 
            ties += 1
    
    p_win = (wins + 0.5 * ties) / N
    BF_odds = (p_win + 1e-8) / (1 - p_win + 1e-8)

    # ==== BOOTSTRAP TIE REPORT ====
    bootstrap_ties = []
    if abs(p_win - 0.5) <= tie_tol:
        # Both top teams tied in bootstrap
        tied_place = float(baseline_df["average_rank"].iloc[0])  # what place they tied for
        bootstrap_ties.append({
            "rank": tied_place,
            "teams": top2
        })

    summary = {
        "team1": top2[0],
        "team2": top2[1],
        "p_win": p_win,
        "BF_odds": BF_odds,
        "N": N,
        "rows_per_draw": B,
        "sample_frac": sample_frac,
    }

    # Flatten bootstrap ties into a readable string or rows
    if bootstrap_ties:
        summary["bootstrap_ties"] = "; ".join(
            [f"Rank {bt['rank']}: {', '.join(bt['teams'])}" for bt in bootstrap_ties]
        )
    else:
        summary["bootstrap_ties"] = "None"

    return baseline_df, pd.DataFrame([summary])

## Task 1 Processing

In [6]:
subview_id = SUBMISSION_VIEWS[
        f"Task {1}"]
submissions_df = select_final_round_submissions(
        syn, subview_id, "Final Round DREAM Olfactory Mixtures Prediction Challenge 2025 - Task 1")

Downloading files: 100%|██████████| 3.91k/3.91k [00:00<00:00, 9.58kB/s, syn68879001]

Downloaded syn68879001 to /Users/mdiaz/.synapseCache/372/163107372/SYNAPSE_TABLE_QUERY_163107372.csv

Downloading files: 100%|██████████| 3.91k/3.91k [00:00<00:00, 9.46kB/s, syn68879001]

In [7]:
submissions_df[1]

,submitterid,id,pearson_correlation,cosine,createdOn,team_id,team_name,createdOn_diff,pearson_rank,cosine_rank,final_rank
7,3516194,9756912,0.752053,0.176111,1754667730603,3516194,nachman.keren,29868397,1.0,1.0,1.0
6,3506852,9756908,0.730260,0.179923,1754667145501,3506852,PL21,30453499,2.0,2.0,2.0
23,3550368,9756933,0.727444,0.184437,1754688407578,3550368,Nylix,9191422,3.0,3.0,3.0

In [ ]:
team_predictions = load_team_predictions(syn, submissions_df[1])
gold_df = load_goldstandard(syn, 1)
team_dfs = split_merged_to_team_dfs(team_predictions, gold_df, INDEX_COL)

In [ ]:
team_dfs.keys()

dict_keys(['nachman.keren', 'PL21', 'Nylix'])

In [ ]:
# Compute baseline
gold_master, team_mats, team_names, baseline_df = compute_baseline(gold_df, team_dfs)

# Compute bootstrap summary -- Pwin
bootstrap_summary = bootstrap_pwin(
    gold_master, team_mats, team_names, baseline_df,
    metrics_on_rows, sample_frac=1.0, N=10000, random_state=98109
)

# Compute 10% bootstrap summary -- Pwin
bootstrap_summary_10 = bootstrap_pwin(
    gold_master, team_mats, team_names, baseline_df,
    metrics_on_rows, sample_frac=0.1, N=10000, random_state=98109
)

In [ ]:
bootstrap_summary

{'team1': 'PL21',
 'team2': 'Nylix',
 'p_win': 0.37135,
 'BF_odds': 0.5907102586381888,
 'N': 10000,
 'rows_per_draw': 31,
 'sample_frac': 1.0,
 'tie_flag': False}

In [ ]:
bootstrap_summary_10

{'team1': 'PL21',
 'team2': 'Nylix',
 'p_win': 0.33155,
 'BF_odds': 0.4959982123420119,
 'N': 10000,
 'rows_per_draw': 3,
 'sample_frac': 0.1,
 'tie_flag': False}

In [ ]:
# Compute bootstrap summary -- pairwise
pairwise_results = bootstrap_pairwise(
    gold_master, team_mats, team_names, baseline_df,
    metrics_on_rows, sample_frac=1.0, N=10000, random_state=98109
)   

# Compute 10% bootstrap summary -- pairwise
pairwise_results_10 = bootstrap_pairwise(
    gold_master, team_mats, team_names, baseline_df,
    metrics_on_rows, sample_frac=0.1, N=10000, random_state=98109
)

KeyboardInterrupt:

In [ ]:
pairwise_results

,team1,team2,wins,ties,p_win,BF_odds,N,rows_per_draw,sample_frac,tie_flag
0,PL21,Nylix,655,9345,0.53275,1.140182,10000,31,1.0,True
1,Nylix,nachman.keren,6465,3228,0.80790,4.205622,10000,31,1.0,False

In [ ]:
pairwise_results_10

,team1,team2,wins,ties,p_win,BF_odds,N,rows_per_draw,sample_frac,tie_flag
0,PL21,Nylix,3101,6251,0.62265,1.650060,10000,3,0.1,False
1,Nylix,nachman.keren,833,5883,0.37745,0.606297,10000,3,0.1,False

In [ ]:
baseline_simultaneous, bootstrap_summary_simultaneous = baseline_and_bootstrap(
    gold_df, team_dfs, metrics_on_rows, INDEX_COL,
    sample_frac=1.0, N=10000, random_state=98109
)

baseline_simultaneous10, bootstrap_summary_simultaneous10 = baseline_and_bootstrap(
    gold_df, team_dfs, metrics_on_rows, INDEX_COL,
    sample_frac=0.1, N=10000, random_state=98109
)

KeyboardInterrupt:

In [ ]:
print("Task 1 100% sample:")
print(baseline_simultaneous)
print(bootstrap_summary_simultaneous)
print("Task 1 10% sample:")
print(baseline_simultaneous10)
print(bootstrap_summary_simultaneous10)

Task 1 100% sample:
            team  avg_pearson  avg_cosine  rank_pearson  rank_cosine  \
1           PL21     0.004392    0.536363           1.0          2.0
2          Nylix     0.004143    0.524684           2.0          1.0
0  nachman.keren    -0.001272    0.586046           3.0          3.0

   average_rank
1           1.5
2           1.5
0           3.0
  team1  team2    p_win  BF_odds      N  rows_per_draw  sample_frac  \
0  PL21  Nylix  0.37135  0.59071  10000             31          1.0

  bootstrap_ties
0           None
Task 1 10% sample:
            team  avg_pearson  avg_cosine  rank_pearson  rank_cosine  \
1           PL21     0.004392    0.536363           1.0          2.0
2          Nylix     0.004143    0.524684           2.0          1.0
0  nachman.keren    -0.001272    0.586046           3.0          3.0

   average_rank
1           1.5
2           1.5
0           3.0
  team1  team2    p_win   BF_odds      N  rows_per_draw  sample_frac  \
0  PL21  Nylix  0.33155  0.495998  10000              3          0.1

  bootstrap_ties
0           None

## Task 2 processing

In [ ]:
subview_id2 = SUBMISSION_VIEWS[
        f"Task {2}"]
submissions_df2 = select_final_round_submissions(
        syn, subview_id2, "Final Round DREAM Olfactory Mixtures Prediction Challenge 2025 - Task 2")

Downloading files:   0%|          | 0.00/1.00 [00:00<?, ?B/s, syn68878940]

Downloaded syn68878940 to /Users/mdiaz/.synapseCache/86/163107086/SYNAPSE_TABLE_QUERY_163107086.csv

Downloading files: 100%|██████████| 2.72k/2.72k [00:00<00:00, 15.8kB/s, syn68878940]

In [ ]:
submissions_df2[1]

,submitterid,id,pearson_correlation,cosine,createdOn,team_id,team_name,createdOn_diff,pearson_rank,cosine_rank,final_rank
4,3506852,9756909,0.789749,0.133586,1754667217304,3506852,PL21,30381696,1.0,1.0,1.0
0,3319559,9756951,0.789684,0.136842,1754695242525,3319559,yuanfang.guan,2356475,2.0,2.0,2.0
12,3550368,9756934,0.785382,0.137598,1754688452187,3550368,Nylix,9146813,3.0,3.0,3.0

In [ ]:
team_predictions2 = load_team_predictions(syn, submissions_df2[1])
gold_df2 = load_goldstandard(syn, 2)
team_dfs2 = split_merged_to_team_dfs(team_predictions2, gold_df2, INDEX_COL)

In [ ]:
# Compute baseline
gold_master2, team_mats2, team_names2, baseline_df2 = compute_baseline(gold_df2, team_dfs2)

# Compute bootstrap summary -- Pwin
bootstrap_summary2 = bootstrap_pwin(
    gold_master2, team_mats2, team_names2, baseline_df2,
    sample_frac=1.0, N=10000, random_state=98109
)

# Compute 10% bootstrap summary -- Pwin
bootstrap_summary2_10 = bootstrap_pwin(
    gold_master2, team_mats2, team_names2, baseline_df2,
    sample_frac=0.1, N=10000, random_state=98109
)

In [ ]:
bootstrap_summary2

{'team1': 'Nylix',
 'team2': 'yuanfang.guan',
 'p_win': 0.4152,
 'BF_odds': 0.7099863250686332,
 'N': 10000,
 'rows_per_draw': 130,
 'sample_frac': 1.0,
 'bootstrap_ties': []}

In [ ]:
bootstrap_summary2_10

{'team1': 'Nylix',
 'team2': 'yuanfang.guan',
 'p_win': 0.3211,
 'BF_odds': 0.47297099023462963,
 'N': 10000,
 'rows_per_draw': 13,
 'sample_frac': 0.1,
 'bootstrap_ties': []}

In [ ]:
# Compute bootstrap summary -- pairwise
pairwise_results2 = bootstrap_pairwise(
    gold_master2, team_mats2, team_names2, baseline_df2,
    metrics_on_rows, sample_frac=1.0, N=10000, random_state=42
)   

# Compute 10% bootstrap summary -- pairwise
pairwise_results2_10 = bootstrap_pairwise(
    gold_master2, team_mats2, team_names2, baseline_df2,
    metrics_on_rows, sample_frac=0.1, N=10000, random_state=42
)

In [ ]:
pairwise_results2

,team1,team2,wins,ties,p_win,BF_odds,N,rows_per_draw,sample_frac,tie_flag
0,Nylix,yuanfang.guan,1907,4408,0.4111,0.698081,10000,130,1.0,False
1,yuanfang.guan,PL21,8567,1132,0.9133,10.534024,10000,130,1.0,False

In [ ]:
pairwise_results2_10

,team1,team2,wins,ties,p_win,BF_odds,N,rows_per_draw,sample_frac,tie_flag
0,Nylix,yuanfang.guan,1658,2863,0.30895,0.447073,10000,13,0.1,False
1,yuanfang.guan,PL21,6989,2276,0.81270,4.339028,10000,13,0.1,False

In [ ]:
baseline_simultaneous2, bootstrap_summary_simultaneous2 = baseline_and_bootstrap(
    gold_df2, team_dfs2, INDEX_COL,
    sample_frac=1.0, N=10000, random_state=98109
)

baseline_simultaneous2_10percent, bootstrap_summary_simultaneous2_10percent = baseline_and_bootstrap(
    gold_df2, team_dfs2, INDEX_COL,
    sample_frac=0.1, N=10000, random_state=98109
)

In [ ]:
print("Task 2 100% sample:")
print(baseline_simultaneous2)
print(bootstrap_summary_simultaneous2)
print("Task 2 10% sample:")
print(baseline_simultaneous2_10percent)
print(bootstrap_summary_simultaneous2_10percent)

Task 2 100% sample:
            team  avg_pearson  avg_cosine  rank_pearson  rank_cosine  \
2          Nylix    -0.000368    0.462619           1.0          2.0
1  yuanfang.guan    -0.004662    0.430524           2.0          1.0
0           PL21    -0.006974    0.467343           3.0          3.0

   average_rank
2           1.5
1           1.5
0           3.0
   team1          team2   p_win   BF_odds      N  rows_per_draw  sample_frac  \
0  Nylix  yuanfang.guan  0.4152  0.709986  10000            130          1.0

  bootstrap_ties
0           None
Task 2 10% sample:
            team  avg_pearson  avg_cosine  rank_pearson  rank_cosine  \
2          Nylix    -0.000368    0.462619           1.0          2.0
1  yuanfang.guan    -0.004662    0.430524           2.0          1.0
0           PL21    -0.006974    0.467343           3.0          3.0

   average_rank
2           1.5
1           1.5
0           3.0
   team1          team2   p_win   BF_odds      N  rows_per_draw  sample_frac  \
0  Nylix  yuanfang.guan  0.3211  0.472971  10000             13          0.1

  bootstrap_ties
0           None

### Print the data and results for winners

In [ ]:
bootstrap_results = {
    "Task_1": {
        "Initial_All": submissions_df[0],
        "Initial_Top3": submissions_df[1],
        "Bootstrap_with_Baseline_100": bootstrap_summary_simultaneous, 
        "Bootstrap_with_Baseline_10": bootstrap_summary_simultaneous10,
        "Pairwise_100": pairwise_results,
        "Pairwise_10": pairwise_results_10,
        "Pwin_100": bootstrap_summary,
        "Pwin_10": bootstrap_summary_10,
    },
    "Task_2": {
        "Initial_All": submissions_df2[0],
        "Initial_Top3": submissions_df2[1],
        "Bootstrap_with_Baseline_100": bootstrap_summary_simultaneous2, 
        "Bootstrap_with_Baseline_10": bootstrap_summary_simultaneous2_10percent,
        "Pairwise_100": pairwise_results2,
        "Pairwise_10": pairwise_results2_10,
        "Pwin_100": bootstrap_summary2,
        "Pwin_10": bootstrap_summary2_10,
    }
}
write_bootstrap_results_to_excel(bootstrap_results, out_file="bootstrap_results.xlsx")

✅ Results written to bootstrap_results.xlsx